apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: edquest/mlflow-ui:v1.0.0  # Replace with your actual image tag
          ports:
            - containerPort: 5000
          command: ["mlflow"]
          args:
            - server
            - --host=0.0.0.0
            - --port=5000
            - --backend-store-uri
            - /mnt/mlflow-data
            - --default-artifact-root
            - file:///mnt/mlflow-data
          volumeMounts:
            - name: mlflow-data
              mountPath: /mnt/mlflow-data
      volumes:
        - name: mlflow-data
          hostPath:
            path: /mnt/mlflow-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000  # Optional; Kubernetes will auto-assign if omitted
