apiVersion: apps/v1
kind: Deployment
metadata:
  name: ice-cream-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ice-cream-model
  template:
    metadata:
      labels:
        app: ice-cream-model
    spec:
      containers:
      - name: ice-cream-model
        image:  edquest/ml-model-server:v1.0.0
        command: ["python"]
        args:
          - mlflow_api.py
        ports:
        - containerPort: 8000
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
          - name: mlflow-data
            mountPath: /mnt/mlflow-data
          - name: config-volume
            mountPath: /app/config
            readOnly: true
      volumes:
        - name: mlflow-data
          hostPath:
            path: /mnt/mlflow-data
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: ice-cream-model-config
---
apiVersion: v1
kind: Service
metadata:
  name: ice-cream-model-service
spec:
  selector:
    app: ice-cream-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-service
spec:
  selector:
    app: ice-cream-model
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
